### ISSUE TITLE
ValueError: More than one match to b'ASC.' / b'XSC.'

### ISSUE THREAD

**Issue by moldovannorbert** [genomematt/xenomapper2#11]
When running xenomapper2 on bams mapped by bwa mem I get the following errors from pylazybam:

> xenomapper2 v2.0rc1 --primary=/scratch-shared/fmlab/nmoldovan/tmp/FM_seq_020/trimmed/7_xenomapper/1_mapping/LP0051_08_L001_primary.bam --secondary=/scratch-shared/fmlab/nmoldovan/tmp/FM_seq_020/trimmed/7_xenoma$
> 
> Traceback (most recent call last):
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/bin/xenomapper2", line 8, in <module>
>     sys.exit(main())
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/lib/python3.10/site-packages/xenomapper2/cli.py", line 193, in main
>     pair_counts, counts, writer = xenomap(primary_bam,
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/lib/python3.10/site-packages/xenomapper2/xenomapper2.py", line 884, in xenomap
>     forward_state, reverse_state = xenomap_states(primary_aligns,
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/lib/python3.10/site-packages/xenomapper2/xenomapper2.py", line 685, in xenomap_states
>     prim_f_AS, prim_f_XS = score_function(prim_f_aligns,
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/lib/python3.10/site-packages/xenomapper2/xenomapper2.py", line 314, in get_bamprimary_AS_XS
>     AS = AS_function(bamprimary[0])
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/lib/python3.10/site-packages/pylazybam/tags.py", line 55, in get_AS
>     raise ValueError(
> ValueError: More than one match to b'ASC.' was found in b'I\x01\x00\x00\x04\x00\x00\x00ASC\x01\'<V\x17\x01\x00S\x00\x97\x00\x00\x00\x04\x00\x00\x00!SC\x01I\xff\xff\xffA01685:16:HGHWVDSX3:1:1258:25373:19100\x00p$
> 

or
> xenomapper2 v2.0rc1 --primary=/scratch-shared/fmlab/nmoldovan/tmp/FM_seq_020/trimmed/7_xenomapper/1_mapping/LP0051_07_L001_primary.bam --secondary=/scratch-shared/fmlab/nmoldovan/tmp/FM_seq_020/trimmed/7_xenoma$
> 
> Traceback (most recent call last):
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/bin/xenomapper2", line 8, in <module>
>     sys.exit(main())
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/lib/python3.10/site-packages/xenomapper2/cli.py", line 193, in main
>     pair_counts, counts, writer = xenomap(primary_bam,
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/lib/python3.10/site-packages/xenomapper2/xenomapper2.py", line 884, in xenomap
>     forward_state, reverse_state = xenomap_states(primary_aligns,
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/lib/python3.10/site-packages/xenomapper2/xenomapper2.py", line 685, in xenomap_states
>     prim_f_AS, prim_f_XS = score_function(prim_f_aligns,
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/lib/python3.10/site-packages/xenomapper2/xenomapper2.py", line 315, in get_bamprimary_AS_XS
>     XS = XS_function(bamprimary[0])
>   File "/gpfs/home1/norbertm/projects/code/core_pipeline_310322/workflow/rules/7_xenomapper/.snakemake/conda/39b62994/lib/python3.10/site-packages/pylazybam/tags.py", line 108, in get_XS
>     raise ValueError(
> ValueError: More than one match to b'XSC.' was found in b'N\x01\x00\x00\x07\x00\x00\x00XSC\x02\'<V\x1b\x01\x00S\x00\x97\x00\x00\x00\x07\x00\x00\x00QSC\x02b\xff\xff\xffA01685:16:HGHWVDSX3:1:1161:21965:27946\x00p$

I am mapping and sorting reads in the previous step by:

> bwa mem {params.ref} {input} \
>         -M \
>         -t {threads} \
>         2> {log} | \
>         samtools sort \
>         -n \
>         -@ {threads} \
>         -o {output} 2>> {log}

Intriguingly this pipeline worked with another batch of files already, but now it is throwing the above error.

Edit: I forgot to add, that we are talking about 150 bp PE seq of genomic data.

**Comment by genomematt** [comment]
I have had a quick look and can't see the obvious problem of there being some other information in the string that gets picked up by the regex search.
If you use samtool view are these the first reads in the file?
The easiest way to proceed if you don't mind is to send me the files so I can reproduce the error. If you can use `samtools view input.bam "chrom:start-end" > output.bam`  with some appropriate region to make a small file that reproduces that would be even better.
If you can't do that, could send me the full SAM for that specific read. You can extract this with `samtools view file.bam | grep -m1 "A01685:16:HGHWVDSX3:1:1161:21965:27946" - `

**Comment by ivanbelzen** [comment]
Hi! I'm encountering the same error

Error message: 
ValueError: More than one match to b'XSC.' was found in b'_\x01\x00\x00\x00\x00\x00\x00XSC\x07(,V/\x01\x00S\x00\x96\x00\x00\x00\x00\x00\x00\x00\xe4RC\x07\xf6\xfe\xff\xffLH00659:469:2357J3LT4:4:1124:26281:5190\x00`\t\x00\x00A\x81\x18\x88\x18\x81\x88AA\x18\x84\x88\x88D(\x12"\x81D\x88\x88\x84\x88\x88\x12!\x81!\x11\x88AA\x18\x81\x88(\x88\x11H\x18(HA\x14\x11\x18H\x88\x81\x11\x11(\x88\x18DD\x18\x84\x81\x88A\x18(HD\x18\x82\x11\x84\x11(\x88D\x81\x14((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((ASS$\x01XSCCXNC\x00XMC\x01XOC\x00XGC\x00NMC\x01MDZ31T118\x00YSS&\x01YTZCP\x00'meaning that more than one value of the tag is presentor that another tag contains a match as part of its value

Reads from sam file: 

LH00659:469:2357J3LT4:4:1124:26281:5190	163	chr1	121852645	44	147M3S	=	121852761	266	CTCTCCTTATTGTTGGGCATTTTGGTTAAGGTCACCCCCATTGATTCTTGAGAGTTTCTCACCTCCCACGTCTCTGGAACTTTCTAGAGGATCCCCCCAACCTCACATCCCCAGAAGATAATTTATTATTGAGAATTGTTTTGGCTACCC	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:294	XS:i:78	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:147	YS:i:292	YT:Z:CP
LH00659:469:2357J3LT4:4:1124:26281:5190	83	chr1	121852761	44	150M	=	121852645	-266	GATAATTTATTATTGAGAATTGTTTTGGCTACCCTAGGTTTTTGTTTTACCATACAAATTGAGAATTATTCTTTAAGTATCTGTGAAGAAATGTTTTAAAAACTTTATGGGGATTGTATTGAATCTGTGGATTCAATGAACTTTGGTAAG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:292	XS:i:67	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:31T118	YS:i:294	YT:Z:CP

The data has been mapped with bowtie to hg38 and to mm39 as specified in the worked example on this github 

bowtie2 --local --threads 7 --reorder \
-x genomes/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index \
-1 Tumor_C10_1.fq.gz \
-2 Tumor_C10_2.fq.gz > bams/Tumor_C10.hg38.bowtie.sam

**Comment by ivanbelzen** [comment]
another occurrance of this error

LH00659:469:2357J3LT4:4:2144:48464:13485	99	chrX	155407193	39	150M	=	155407388	345	TGTTTTTGTGCCAGTACCATGCTGTTTTGGTTACTGTAGCCTTGTAGTATAGTTTCAGGTCAGGTAGTGTGATGCCTCCAGCTTTGTTCTTTTTGCTTAGGGTTACTTTGGTGATTCATGCTCTTTTTTGGTTGCATATGAATTTTAGAA	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:300	XS:i:112	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:300	YT:Z:CP
LH00659:469:2357J3LT4:4:2144:48464:13485	147	chrX	155407388	39	150M	=	155407193	-345	GGAATAGCATTGAATCTATAAATTTCTTTGGTCAGTATGGCCATTTTAACAATATTAATTATTTCAATTCATAAGCATGGGGTGTTTTACCATTATGTTTGTGTCATCTCTGATTTATCTCAGCAGTGTTTTATAGTTCTCCTTGTAGAG	IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII	AS:i:300	XS:i:95	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:300	YT:Z:CP

**Comment by genomematt** [comment]
Bowtie now appends the pair tag to the bam so there are two XC tags in the bam. As a temporary hack you should be able to covert to SAM and back to BAM and it should remove. I will be able to do a more permanent fix early in June.

--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=--=-=

A/Prof Matthew Wakefield PhD
Stafford Fox Principal Research Fellow of Ovarian Cancer Biology and Genomics
Bioinformatics, WEHI
***@***.***

The Royal Women’s Hospital and Mercy Hospital for Women
Department of Obstetrics, Gynaecology, and Newborn Health.
University of Melbourne
***@***.***
M +61 402 916 018
________________________________

**Comment by ivanbelzen** [comment]
Thank you for the input! I have tried this (see below) but unfortunately it still gives the same error 

 samtools view -h bowtie.bam -@ 4 | samtools view -@4 -b -o bowtie.redo.bam
